### ISSUE TITLE
The Discord invitation link is broken

### ISSUE THREAD

**Issue by kondounagi** [TREC-RAG/trec-rag.github.io#1]
The side bar of the hosted website has a discord invitation link.
<img width="296" alt="image" src="https://github.com/TREC-RAG/trec-rag.github.io/assets/38452345/8da21243-266c-4f37-8bf8-d07ec2a2366f">

The invitation link is set with the code below.

https://github.com/TREC-RAG/trec-rag.github.io/blob/62b3ee842335b18f74588efaa2e2bd4730ee4ea6/docs/_config.yml#L134

However, the invitation link is broken.

https://discord.com/invite/2JpTEZyG7c

**Comment by thakur-nandan** [comment]
Hi @kondounagi, the link seems to work for me.

Were you able to join the discord channel?

**Comment by kondounagi** [comment]
I tried the link again, and it seems to be working well.
It would be a temporal problem.
Thanks!
